# Generated by Django 5.0.1 on 2024-12-05 11:02

from django.db import migrations
from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib.auth.hashers import make_password


def generate_superuser(apps, schema_editor):
    """Create a new superuser"""
    User = apps.get_model("users", "User")
    superuser = User(
        email=settings.SUPERUSER_EMAIL,
        password=make_password(settings.SUPERUSER_PASSWORD),
        is_staff=True,
        is_superuser=True,
    )
    superuser.save()


def remove_superuser(apps, schema_editor):
    """Remove the superuser created in the previous migration"""
    User = apps.get_model("users", "User")
    try:
        superuser = User.objects.get(email=settings.SUPERUSER_EMAIL)
        superuser.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.RunPython(generate_superuser, reverse_code=remove_superuser),
    ]
