# Generated by Django 5.0.1 on 2024-12-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_admin_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.TextField(blank=True, default="", max_length=2048, null=True),
        ),
    ]
