# Generated by Django 5.0.1 on 2024-12-09 10:49

import secrets
import string
import sys
from django.db import migrations
from datetime import timedelta, datetime
from django.conf import settings


def generate_random_name(length=5):
    """Generate a random name-like string"""
    # Ensure it starts with a capital letter
    return "".join(
        string.ascii_lowercase[secrets.randbelow(len(string.ascii_lowercase))]
        for _ in range(length - 1)
    )


def create_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    start_date = datetime(2024, 11, 1)
    current_date = datetime.now()

    # Calculate the total seconds between start and current date
    time_between_dates = current_date - start_date
    days_between_dates = time_between_dates.days

    for i in range(20):
        first_name = generate_random_name(secrets.randbelow(8) + 4)
        last_name = generate_random_name(secrets.randbelow(10) + 4)

        random_days = secrets.randbelow(days_between_dates)
        random_seconds = secrets.randbelow(86400)  # Random seconds in a day

        # Create a random date within the range
        date_joined = start_date + timedelta(days=random_days, seconds=random_seconds)
        email = f"example_{i+1}@email.com"
        user_id = (
            secrets.randbelow(9000000) + 1000000
        )  # Generate a random 7-digit number
        avatar = f"https://avatars.githubusercontent.com/u/{user_id}?v=4"
        user = User(
            email=email,
            password=settings.SUPERUSER_PASSWORD,
            avatar=avatar,
            date_joined=date_joined,
            first_name=first_name,
            last_name=last_name,
        )
        user.save()


def delete_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    emails = [f"example_{i+1}@email.com" for i in range(20)]
    User.objects.filter(email__in=emails).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]
    operations = (
        [
            migrations.RunPython(create_users, reverse_code=delete_users),
        ]
        if "test" not in sys.argv
        else []
    )
