version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=production
        - SECRET_KEY=U.gM-V)D5Z{CA303?eJ%Kr-}48CfM#p}0GzcE[BD*pa;;PPwrq/U7J!n{e9H
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
