# Generated by Django 5.0.1 on 2024-12-14 09:58

import detect_ai_backend.api_keys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="api_key",
            field=models.CharField(
                default=detect_ai_backend.api_keys.models.api_key_generator,
                editable=False,
                max_length=42,
            ),
        ),
    ]
