# Generated by Django 5.0.1 on 2024-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
