# Generated by Django 5.0.1 on 2024-12-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0002_alter_apikey_api_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apikey",
            old_name="is_default",
            new_name="is_active",
        ),
    ]
