# Generated by Django 5.0.1 on 2024-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0002_apikey_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="last_used",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="apikeylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("pending", "Pending"),
                ],
                default="pending",
            ),
        ),
    ]
