# Generated by Django 5.0.1 on 2024-12-14 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
