# Generated by Django 5.0.1 on 2024-12-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_history_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
