name: CI-dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==4.0.1
    - name: Run Flake8
      run: |
        flake8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: github.event_name == 'push'  # Only set up Docker Buildx on push events

    - name: Build Image
      uses: docker/build-push-action@v6
      if: github.event_name == 'push'  # Only set up Docker Buildx on push events
      with:
          load: true
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
            latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ENV=production
          outputs: type=docker,dest=/tmp/image.tar

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      if: github.event_name == 'push'
      with:
          image-ref: latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

    - name: Upload Image
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push'
      with:
          name: image
          path: /tmp/image.tar
